BudgetUnit.find_or_create_by(name: "")
BudgetUnit.find_or_create_by(name: "1曲")
BudgetUnit.find_or_create_by(name: "1時間")
BudgetUnit.find_or_create_by(name: "日")
BudgetUnit.find_or_create_by(name: "月")
BudgetUnit.find_or_create_by(name: "総額")